dataset_root: ./Data
general_seed: 2025

input_dim: 10
features: 
  0: 
    - name: bar_x
    - definition: Horizontal x-axis coordinate of the barbell end in the image/frame (lateral-view).
  1: 
    - name: bar_y
    - definition: Vertical y-axis coordinate of the barbell end in the image/frame (lateral-view).
  2: 
    - name: barx/bar_y
    - definition: Ratio of bar end coordinates, bar_x divided by bar_y; dimensionless.
  3: 
    - name: left_shoulder_y
    - definition: Vertical y-axis coordinate of the left shoulder in the rear (head-back) view.
  4: 
    - name: right_shoulder_y
    - definition: Vertical y-axis coordinate of the right shoulder in the rear (head-back) view.
  5: 
    - name: left_dist
    - definition: Perpendicular distance from the wrist to the extended line connecting the two shoulder joints in the top-down view.
  6: 
    - name: right_dist
    - definition: Perpendicular distance from the wrist to the extended line connecting the two shoulder joints in the top-down view.
  7: 
    - name: left_elbow
    - definition: Elbow joint angle at the left side in the rear (head-back) view.
  8: 
    - name: left_shoulder
    - definition: Shoulder joint angle at the left side in the rear (head-back) view, defined by connecting line between the two shoulder joints and upper arm.
  9: 
    - name: right_elbow
    - definition: Elbow joint angle at the right side in the rear (head-back) view.
  10: 
    - name: right_shoulder
    - definition: Shoulder joint angle at the right side in the rear (head-back) view, defined by connecting line between the two shoulder joints and upper arm.
  11: 
    - name: left_torso-arm
    - definition: Angle at the left armpit between the torso axis and the left upper arm in the top-down view.
  12: 
    - name: right_torso-arm
    - definition: Angle at the right armpit between the torso axis and the right upper arm in the top-down view.

mistakes:
  0:
    - name: wrist_bending_backward
    - definition: 
  1:
    - name: tilting_to_the_left
    - definition: 
  2:
    - name: tilting_to_the_right
    - definition: 
  3:
    - name: scapular_protraction
    - definition: 
  4:
    - name: elbows_flaring
    - definition: 

flow_dim: 128 # embedding dim flow into/in diffusion
dataset: 
  split_base_num: 36
  caption: Caption_explain_no_barbell
vae: 
  block_hidden_size: 128 # hidden size of the blocks in the network
  num_residual_layers: 3 # number of residual layers in the model
  res_hidden_size: 256 # hidden size of the residual layers
  embedding_dim: 64 # dimension of the embeddings
  epoch: 30000
diffusion: 
  denoiser: DiT
  backbone: flowmatching
